version: '3.8'

services:
  eureka-server:
    build:
      context: ./discovery-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  configserver:
    build:
      context: ./config-server
      dockerfile: Dockerfile
    environment:
      EUREKA_INSTANCE_HOSTNAME: eureka-server
      KEYCLOAK_ISSUER: keycloak
      KAFKA_HOST: kafka
      MYSQL_HOST: mysql
      NGINX_HOST: frontapp
    ports:
      - "8888:8888"

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    environment:
      CONFIG_HOST: configserver
    ports:
      - "9000:9000"
    depends_on:
      - configserver
      - eureka-server

  keycloak:
    build:
      context: ./keycloakauthServer
      dockerfile: Dockerfile
    environment:
      MYSQL_HOST: mysql
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8181:8080"
    depends_on:
      - mysql

  kafka:
    image: wurstmeister/kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9092:9092"

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

##  chmod +x init-db.sh
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: univeralmm
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./keycloakdb.sql:/docker-entrypoint-initdb.d/keycloakdb.sql
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  keycloakuser:
    build:
      context: ./keycloakuser
      dockerfile: Dockerfile
    environment:
      CONFIG_HOST: configserver
    depends_on:
      - configserver
      - mysql
      - gateway
      - eureka-server

  notification:
    build:
      context: ./notification
      dockerfile: Dockerfile
    environment:
      CONFIG_HOST: configserver
    depends_on:
      - configserver
      - mysql
      - gateway
      - eureka-server

  stock:
    build:
      context: ./stock
      dockerfile: Dockerfile
    environment:
      CONFIG_HOST: configserver
    depends_on:
      - configserver
      - mysql
      - gateway
      - eureka-server

  frontapp:
    build:
      context: ./phoenixfront
      dockerfile: Dockerfile
    environment:
      KEYCLOAK_HOSTNAME: keycloak
      API_HOSTNAME: gateway
    ports:
      - "80:80"
    command: [ "/bin/sh", "-c", "sed -i 's|__KEYCLOAK_HOSTNAME__|'${KEYCLOAK_HOSTNAME}'|g' /usr/share/nginx/html/main.*.js && sed -i 's|__API_HOSTNAME__|'${API_HOSTNAME}'|g' /usr/share/nginx/html/main.*.js && nginx -g 'daemon off;'" ]